input_query_path = "datasets/topiocqa/dev_rel_token.json"
index_dir_path = "datasets/topiocqa/indexes/bm25"

query_type = "raw"
bm25_k1 = 0.9
bm25_b = 0.4
top_k = 100
rel_threshold = 1
add_topic = false
use_answer = false
use_last_response = false

output_dir_path = "output/topiocqa/bm25"
gold_qrel_file_path = "datasets/topiocqa/dev_rel_token_gold.trec"