input_query_path = "datasets/topiocqa/dev_new.json"
index_dir_path = "datasets/topiocqa/indexes/bm25"

query_type = "convq"
bm25_k1 = 0.9
bm25_b = 0.4
top_k = 100
rel_threshold = 1
add_topic = false
use_PRF = false


output_dir_path = "output/topiocqa/bm25"
gold_qrel_file_path = "datasets/topiocqa/dev_gold.trec"
PRF_file = "output/topiocqa/bm25/dev_rel_label_rawq_token.json" 

